// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ8H5jHKuI1B2LLQpyqpK02V5F_qKjYw4',
    appId: '1:721590978783:web:13cbaaa6498f1868c3416a',
    messagingSenderId: '721590978783',
    projectId: 'nasabot-5414b',
    authDomain: 'nasabot-5414b.firebaseapp.com',
    databaseURL: 'https://nasabot-5414b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nasabot-5414b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwZUUVX7WrnrMepteVso2NQDQ3Nqz5EQ',
    appId: '1:721590978783:android:e33df22922d87131c3416a',
    messagingSenderId: '721590978783',
    projectId: 'nasabot-5414b',
    databaseURL: 'https://nasabot-5414b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nasabot-5414b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjk_HQRjdZJPJLekHEBxG8IkRIrzimt44',
    appId: '1:721590978783:ios:d84cb67129fc6bf5c3416a',
    messagingSenderId: '721590978783',
    projectId: 'nasabot-5414b',
    databaseURL: 'https://nasabot-5414b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nasabot-5414b.appspot.com',
    iosBundleId: 'com.tanjim.trasmit',
  );
}
